services:
  postgres-db:
    container_name: postgres-container1
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: custom_auth
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: