spring.application.name=custom_auth

# Datasource (PostgreSQL)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=admin@123
spring.datasource.url=jdbc:postgresql://localhost:5432/custom_auth
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



# JWT Security
application.security.jwt.signing-key=5heUCJxsTsaYyTE6+XB+tnpvdZkttNv5PBWHe9v9q73kGjDa2+UI2YQMWPj1Fpec
application.security.jwt.expiration-ms=600000

# Email Configuration (Gmail Example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rudroaiub@gmail.com
spring.mail.password=anik
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


# Application Configuration
app.base-url=http://localhost:8080
app.verification.expiration-minutes=10
app.verification.resend-interval-minutes=5